# Generated by Django 3.1.4 on 2021-02-02 05:35

from django.db import migrations
from django.utils import timezone



def populate_db(apps, schema_editor):
    Expenses = apps.get_models('financial_tracking', 'Expenses')
    Income = apps.get_models('financial_tracking', 'Income')


    expense_1 = Expenses(description="Dr. Pepper", date=timezone.now())
    expense_1.save()

    income_1 = Income(description="AMLC pay", date=timezone.now())
    income_1.save()




class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(populate_db)    
            ]
