# Generated by Django 3.1.4 on 2021-02-02 05:55

from django.db import migrations
from django.utils import timezone



def populate_db(apps, schema_editor):
    Expenses = apps.get_model('financial_tracking', 'Expenses')
    Income = apps.get_model('financial_tracking', 'Income')


    expense_1 = Expenses(description="Dr. Pepper", price='1.25', date=timezone.now())
    expense_1.save()

    
    expense_2 = Expenses(description="Taco Time", price='1.25', date=timezone.now())
    expense_2.save()


    income_1 = Income(description="AMLC pay", price='1.25', date=timezone.now())
    income_1.save()

class Migration(migrations.Migration):

    dependencies = [
        ('financial_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)


            ]
